- name: "generate war file"
  hosts: local
  become: true
  vars:
          gitdir: "/tmp/BookzyBookShop2"
  tasks:
          - name: "install maven"
            yum:
                    name: maven
          - name: "clone the addressbook project"
            git:
                    repo: 'https://github.com/elmonje/BookzyBookShop.git'
                    dest: "{{ gitdir }}"
                    version: "main"   
- name: "setup webserver and deploy WAR"
  hosts: ApacheServer01 
  become: true
  vars:
          gitdir: "/tmp/BookzyBookShop2"
  tasks:
          - name: "enable tomcat service"
            service:
                    name: httpd
                    state: started
                    enabled: yes
          - name: "restart tomcat service post deployment"
            service:
                    name: httpd
                    state: restarted
  
          - name: "deploy WAR file"
            copy:
                    src: "{{ gitdir }}/target/BookzyBookShop.war"
                    dest: "/opt/tomcat/webapps/BookzyBookShop.war"
            notify: "restart tomcat service post deployment"

          - name: "stop apache"
            shell: "sudo /opt/tomcat/bin/shutdown.sh"

          - name: ==> sleep 5s
            command: sleep 5s
     
          - name: "start apache"
            shell: "sudo /opt/tomcat/bin/startup.sh"

          - name: ==> sleep 5s
            command: sleep 5s
