- name: "generate war file"
  hosts: local
  become: true
  vars:
          gitdir: "/tmp/BookzyBookShop2"
  tasks:
          - name: "install maven"
            yum:
                    name: maven
          - name: "Clonando el proyecto BookzyBookShop del git"
            git:
                    repo: 'https://github.com/elmonje/BookzyBookShop.git'
                    dest: "{{ gitdir }}"
                    version: "main"
          - name: "compile the addressbook project"
            command:
                    chdir: "{{ gitdir }}"
                    cmd: "sudo mvn package"                    
- name: "Configurar el Tomcat Remoto y Desplegando WAR"
  hosts: UbuntuTomcatNode 
  become: true
  vars:
          gitdir: "/tmp/BookzyBookShop2"
  tasks:
          - name: "Instalando Tomcat"
            apt:
                    name: tomcat9
                    update_cache: yes
            notify: "enable tomcat service"
          - name: "Desplegando el War"
            copy:
                    src: "{{ gitdir }}/target/BookzyBookShop.war"
                    dest: "/var/lib/tomcat9/webapps/BookzyBookShop.war"
            notify: "Reseteando El Servicio Toncat despues del despiege"
  handlers:
          - name: "enable tomcat service"
            service:
                    name: tomcat9
                    state: started
                    enabled: yes
          - name: "restart tomcat service post deployment"
            service:
                    name: tomcat9
                    state: restarted
