- name: "generate war file"
  hosts: local
  become: true
  vars:
          gitdir: "/tmp/addressbook-project-1"
  tasks:
          - name: "install maven"
            apt:
                    name: maven
          - name: "clone the addressbook project"
            git:
                    repo: 'https://github.com/elmonje/BookzyBookShop'
                    dest: "{{ gitdir }}"
                    version: "main"
          - name: "compile the addressbook project"
            command:
                    chdir: "{{ gitdir }}"
                    cmd: "mvn package"
- name: "setup webserver and deploy WAR"
  hosts: ApacheServer01 
  become: true
  vars:
          gitdir: "/tmp/addressbook-project-1"
  tasks:
          - name: "install tomcat9"
            apt:
                    name: tomcat9
                    update_cache: yes
