- name: "generate war file"
  hosts: local
  become: true
  vars:
          gitdir: "/tmp/addressbook-project-1"
  tasks:
          - name: "clone the addressbook project"
            git:
                    repo: 'https://github.com/elmonje/BookzyBookShop'
                    dest: "{{ gitdir }}"
                    version: "main"
          - name: "compile the addressbook project"
            command:
                    chdir: "{{ gitdir }}"
                    cmd: "mvn package"                    
