- name: "generate war file"
  hosts: local
  become: true
  vars:
          gitdir: "/tmp/BookzyBookShop2"
  tasks:
          - name: "clone the addressbook project"
            git:
                    repo: 'https://github.com/elmonje/BookzyBookShop.git'
                    dest: "{{ gitdir }}"
                    version: "main"   
          - name: "compile the addressbook project"
            command:
                    chdir: "/tmp/BookzyBookShop2/src"
                    cmd: "mvn package"
