- name: "generate war file"
  hosts: local
  become: true
  vars:
          gitdir: "/tmp/BookzyBookShopF12"
  tasks:
          - name: "install maven"
            yum:
                    name: maven
          - name: "Clonando el proyecto BookzyBookShop del git"
            git:
                    repo: 'https://github.com/elmonje/BookzyBookShop.git'
                    dest: "{{ gitdir }}"
                    version: "main"
                    accept_hostkey: yes
                    force: yes                    
          - name: "compile the addressbook project"
            command:
                    chdir: "{{ gitdir }}"
                    cmd: "mvn package"
- name: "Configurar el Tomcat Remoto y Desplegando WAR"
  hosts: UbuntuTomcatNode 
  become: true
  vars:
          gitdir: "/tmp/BookzyBookShopF12"
  tasks:
          - name: "Instalando Tomcat"
            apt:
                    name: tomcat9
                    update_cache: yes
            notify: "enable tomcat service"
          - name: "Desplegando el War"
            ansible.builtin.copy:
                    src: "{{ gitdir }}/target/BookzyBookShop.war"
                    dest: "/var/lib/tomcat9/webapps/BookzyBookShop.war"
            notify: "Copiando el .war al servidor Tomcat"
            ignore_errors: yes             
