- name: "generate war file"
  hosts: local
  become: true
  vars:
          gitdir: "/tmp/addressbook"
  tasks:
          - name: "install maven"
            yum:
                    name: maven
          - name: "Clonando el proyecto BookzyBookShop del git"
            git:
                    repo: 'https://github.com/elmonje/addressbook.git'
                    dest: "{{ gitdir }}"
                    version: "main"
                    accept_hostkey: yes
                    force: yes                    
          - name: "compile the addressbook project"
            command:
                    chdir: "{{ gitdir }}"
                    cmd: "mvn package"
- name: "Configurar el Tomcat Remoto y Desplegando WAR"
  hosts: UbuntuTomcatNode 
  become: true
  vars:
          gitdir: "/tmp/addressbook"
  tasks:
          - name: "Instalando Tomcat"
            apt:
                    name: tomcat9
                    update_cache: yes
            notify: "enable tomcat service"
          - name: "deploy WAR file"
            copy:
                    src: "{{ gitdir }}/target/addressbook.war"
                    dest: "/var/lib/tomcat9/webapps/addressbook.war"            
  handlers:
          - name: "compile the addressbook project3"            
            shell: "whoami > /tmp/datos2.txt"
            register: "output"            
          - name: "enable tomcat service"
            service:
                    name: tomcat9
                    state: started
                    enabled: yes
          - name: "restart tomcat service post deployment"
            service:
                    name: tomcat9
                    state: restarted            
