- name: "generate war file"
  hosts: local
  become: true
  vars:
          gitdir: "/tmp/BookzyBookShop"
  tasks:
          - name: "install maven"
            apt:
                    name: maven
          - name: "clone the addressbook project"
            git:
                    repo: 'https://github.com/elmonje/BookzyBookShop.git'
                    dest: "{{ gitdir }}"
                    version: "main"
          - name: "compile the addressbook project"
            command:
                    chdir: "{{ gitdir }}"
                    cmd: "mvn package"
- name: "setup webserver and deploy WAR"
  hosts: ApacheServer01 
  become: true
  vars:
          gitdir: "/tmp/BookzyBookShop"
  tasks:
          - name: "install tomcat9"
            apt:
                    name: tomcat9
                    update_cache: yes
            notify: "enable tomcat service"
          - name: "deploy WAR file"
            copy:
                    src: "{{ gitdir }}/target/BookzyBookShop.war"
                    dest: "/var/lib/tomcat9/webapps/BookzyBookShop.war"
            notify: "restart tomcat service post deployment"
  handlers:
          - name: "enable tomcat service"
            service:
                    name: tomcat9
                    state: started
                    enabled: yes
          - name: "restart tomcat service post deployment"
            service:
                    name: tomcat9
                    state: restarted
