- name: "generate war file"
  hosts: local
  become: true
  vars:
          gitdir: "/tmp/addressbook2"
  tasks:
          - name: "install maven"
            yum:
                    name: maven
          - name: "clone the addressbook project"
            git:
                    repo: 'https://github.com/upshiftnow/addressbook'
                    dest: "{{ gitdir }}"
                    version: "main"   
          - name: "compile the addressbook project"
            command:
                    chdir: "{{ gitdir }}"
                    cmd: "mvn package"
